// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quiybyyznvgolbcaexwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1aXlieXl6bnZnb2xiY2FleHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDIyNDcsImV4cCI6MjA2NzAxODI0N30.mKEMWmB3JE2fs5Taskn6hXvrXD0UoO3BbOryRI5wHuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});